version: "3"
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
#   restart: always
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
 #  volumes:
 #    - .:/app
    links:
      - "mongo"
    depends_on:
      - "mongo"
  mongo:
    container_name: mongo
    image: mongo:3.6-stretch
#    restart: always
    command: [--auth]
#    volumes:
#      - ./docker-build/mongo/data:/data/db
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DOCKER_MONGO_ROOT_USERNAME-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${DOCKER_MONGO_ROOT_PASSWORD-secret}
